name: PR validation

on:
  pull_request:
    branches:
      - develop

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Printing Hello
        run: echo "Hello from GitHub Actions"